# Если нашли баг, или что-то хотите увидеть в плагине, можете написать мне в Discord; shved255
# Что будет написано в чате? Работают цвета. Используйте плейсхолдер {TIME}, чтобы указать оставшиеся время до конца проверки игрока. Плейсхолдер распостраняется только на этот конфиг.
Message: "&fСкрафтите верстак. У Вас есть &c{TIME} &fсекунд."
# Включить ли БоссБар? (true || false)
BossBarDisplay: true 
# Что будет написано если игрок не прошел проверку? Также работают цвета.
Kick: "&8&o&nВы провалили проверку, возможно Вы &f&o&lбот&8&o&n&n."
# Что будет написано если игрок прошел проверку? Также работают цвета.
Success: "&aВы прошли проверку!"
# Время, сколько будет у игрока на крафт.
Time: 60 
# Включить ли таймер секунд до конца проверка на шкале опыта? ВНИМАНИЕ!!! Если Вы используете на игровом сервере, желательно выключить. Потому что будет пропадать опыт у игроков после проверки.
LevelEnable: false
# Это время, сколько не нужно бует проходить проверку. Если хотите отключить, поставьте справа от Enabled false. Достпуно только true или false.
HoursLogin:
    # Время в часах скоолько не нужно будет проходить проверку. В данном случае 72 часа = 3 дня. Если хотите отклюяить - вписывайте 0.
    Time: 72
    # Команды которые вводятся после проверки. Есть от имени игрока, и от консоли. Команды также выполнятся при входе. Если не нужны команды, оставьте как есть.
Commands:
    # Команды выполняемые от имени сервера. Используйте (PLAYER) чтобы использовать ник игрока который прошел проверку. Плейсхолдер работает только в этом конфиге. Пример: [tp (PLAYER) 0 0 0 ] - Телепортирует игрока на координаты 0 0 0.
    ServerCommands: []
    # Команды выполняемые от имени игрока.
    PlayerCommands: []    
Subject:
    # Предмет который будет выдаваться при входе игроку. Работает только писменное айди предметов. Например WOOD = доски. (Перечисление айди не работает, доступен только один предмет на выдачу).
    Give: WOOD
    # Количество выдаваемых предметов. Сверху указанное айди блока = WOOD, значит будет при входе выдаваться 4 доски.
    GiveCount: 4
    # Что должен скрафтить игрока. В конфигурации выдается 4 дубовых доски, если игрока скрафтил предмет который указан ниже под предлогом UnGive (в моем случае WORKBENCH, значит игрок должен скрафтить верстак). (Перечисление айди не работает, доступен только один предмет на проверку).
    Ungive: WORKBENCH 
BossBar:
    # Что будет написано на боссбаре? Также работают цвета. Используйте плейсхолдер {TIME}, чтобы указать оставшиеся время до конца проверки игрока. Плейсхолдер распостраняется только на этот конфиг.
    BossBar: "&fЭто проверка, у Вас для крафта верстака есть &c{TIME} &fсекунд."  
    # Цвета боссбара.    
    BossBarColor: RED # RED, GREEN, BLUE, YELLOW, PURPLE, WHITE, ORANGE
    # Стиль боссбара.
    BossBarStyle: SOLID # SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20